package com.uet.VolunteerHub.enums;

public enum NotificationType {
    POST_LIKE, POST_COMMENT, EVENT_START_REMINDER,
    EVENT_END_REMINDER, EVENT_JOIN_APPROVED, EVENT_JOIN_REJECTED,
    ROLE_REQUEST_APPROVED, ROLE_REQUEST_REJECTED, NEW_FOLLOWER, COMMENT_REPLY,
    OTHER, SYSTEM_ANNOUNCEMENT, NORMAL
}
