package com.uet.VolunteerHub.enums;

public enum NotificationType {
    POST_LIKE, POST_COMMENT, COMMENT_REPLY,
    EVENT_START_REMINDER, EVENT_END_REMINDER,
    EVENT_JOIN_APPROVED, EVENT_JOIN_REJECTED,
    EVENT_APPROVED, EVENT_REJECTED, EVENT_CANCELLED,
    EVENT_JOIN_REQUEST,
    MANAGER_ROLE_REQUEST,
    ROLE_REQUEST_APPROVED, ROLE_REQUEST_REJECTED,
    NEW_FOLLOWER,
    OTHER, SYSTEM_ANNOUNCEMENT, NORMAL
}
