export { default as Header } from "./Header";
export { default as HeroSection } from "./HeroSection";
export { default as FeaturesSection } from "./FeaturesSection";
export { default as Marquee } from "./Marquee";
export { default as AboutSection } from "./AboutSection";
export { default as ProjectsSection } from "./ProjectsSection";
export { default as Banner } from "./Banner";
export { default as CTASection } from "./CTASection";
export { default as Footer } from "./Footer";
